version: 2
updates:
# Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
       python-packages:
         update-types:
           - "minor"
           - "patch"

  - package-ecosystem: "docker"
    directory: "/dockerfile-primo"
    schedule:
      interval: "daily"
    groups:
      lambda-extension:
        patterns:
          - "lambda-extension"
      python-version:
        patterns:
          - "python"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/dockerfile-secondo"
    schedule:
      interval: "daily"
    groups:
      lambda-extension:
        patterns:
          - "lambda-extension"
      python-version:
        patterns:
          - "python"
        update-types:
          - "minor"
          - "patch"
