version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dockerfile-primo"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/dockerfile-secondo"
    schedule:
      interval: "daily"