version: 2
updates:
# Python
  - package-ecosystem: "pip"
    directory: "/python-*/Pipfile*"
    schedule:
      interval: "daily"
    groups:
       python-packages:
         update-types:
           - "minor"
           - "patch"

  # actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/*/action.yml"
    schedule:
      interval: "weekly"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"

  # docker
  - package-ecosystem: "docker"
    directory: "/dockerfile-*/Dockerfile"
    schedule:
      interval: "daily"
    groups:
      lambda-extension:
        patterns:
          - "lambda-extension"
      python-version:
        patterns:
          - "python"
        update-types:
          - "minor"
          - "patch"
