version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dockerfile-primo"
    schedule:
      interval: "daily"
    groups:
      lambda-extension:
        patterns:
          - "lambda-extension"
      python-version:
        patterns:
          - "python"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/dockerfile-secondo"
    schedule:
      interval: "daily"
    groups:
      lambda-extension:
        patterns:
          - "lambda-extension"
      python-version:
        patterns:
          - "python"
        update-types:
          - "minor"
          - "patch"

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:40"
      timezone: "Europe/Rome"
    groups:
      pip:
        update-types:
          - "minor"
          - "patch"