name: Prod Apply workflow

on:
  pull_request:
    types:
    - closed

jobs:
  prod-apply:
    if: github.ref_name == 'main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: prod-plan

    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Terraform Apply
        run: |
          echo "Terraform Apply"