name: CI
run-name: my CI run name ${{ github.ref_name }}

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git current branch
        run: |
          git branch
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
