name: test matrix

on:
  workflow_dispatch:
    inputs:
      aws_regions:
        description: "AWS regions (comma separated)"
        required: false
        default: "us-east-1"
      test:
        type: choice
        description: Is this a test?
        options: 
        - "yes"
        - "no"
        default: "no"

# create action to check region name is valid
env:
  AWS_REGIONS: "us-east-1, eu-west-1"
  TERRAFORM_VERSION: ~1.5

jobs:
  #compute_regions:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    AWS_REGIONS: ${{ env.AWS_REGIONS }}
  #  steps:
  #    - name: Compute outputs
  #      run: |
  #        echo "ciao"

  plan:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          program: [program1, program2, program3]
          stage: [dev, staging, prod]
          region: [us-east-1, eu-west-1]
      environment: "${{ matrix.stage }}-plan"

      steps:
        - name: Check out repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: get region prefix
          id: region-prefix
          run: |
            echo "region_prefix=$(awk -F- '{print $1}' <<< "${{ matrix.region }}")" >> "$GITHUB_OUTPUT"

        - name: Current item
          run: |
            echo "${{ steps.region-prefix.outputs.region_prefix }} - ${{ matrix.program }} - ${{ matrix.stage }}"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "TEST=$((${{ inputs.test }} == "yes" ? "[TEST] " : "")); $TEST 🚑 Support Week:"


