name: test paths 1

on:
  push:
    paths:
      - "folder1/**"

jobs:
  dosmth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: smth has changed
        run: |
          echo "changed files in folder1"
