name: test matrix

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: ~1.5

jobs:
  plan:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          program: [program1, program2, program3]
          stage: [dev, staging, prod]
          region: [us-east-1]
      environment: "${{ matrix.stage }}-plan"

      steps:
        - name: Check out repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Current item
          run: |
            echo "${{ matrix.region }} - ${{ matrix.program }} - ${{ matrix.stage }}""
