name: test matrix

on:
  workflow_dispatch:

env:
  AWS_REGIONS: "us-east-1, eu-west-1"
  TERRAFORM_VERSION: ~1.5

jobs:
  compute_regions:
    runs-on: ubuntu-latest
    outputs:
      AWS_REGIONS: ${{ env.AWS_REGIONS }}
    steps:
      - name: Compute outputs
        run: |
          echo "AWS_REGIONS=${{ env.AWS_REGIONS }}" >> $GITHUB_OUTPUT

  plan:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          program: [program1, program2, program3]
          stage: [dev, staging, prod]
          region: ["${{ needs.compute_regions.outputs.AWS_REGIONS }}"]
      environment: "${{ matrix.stage }}-plan"

      steps:
        - name: Check out repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Current item
          run: |
            echo "${{ matrix.region }} - ${{ matrix.program }} - ${{ matrix.stage }}"
